Description: Add a redirect rule to an existing ALB listerner identified by its ARN
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  RedirectFromHost:
    Description: The host name we want to redirect from
    Type: String
  RedirectToHost:
    Desccription: The host name we want to redirect to
    Type: String
  ListernerArn:
    Description: The ARN of the listener this redirect rule should be applied to
    Type: String
Resources:
  Type: AWS::ElasticLoadBalancingV2::ListenerRule
  Properties: 
    Actions: 
      - Type: Redirect
        RedirectConfig:
          Protocol: "HTTPS"
          Port: "443"
          Host: !Ref RedirectToHost
          StatusCode: "HTTP_302"
    Conditions: 
      - Field: "host-header"
        HostHeaderConfig:
          Values:
            - !Ref RedirectFromHost
    ListenerArn: !Ref ListernerArn
    Priority: 1